version: "3.7"
services:

  ## PHP-FPM Container ############
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    image: php-fpm
    container_name: LaravelVue-php-fpm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - LaravelVue-network

  ## NGINX Container #############
  nginx:
    image: nginx:1.19-alpine
    container_name: LaravelVue-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - LaravelVue-network

  # MySQL Container
  mysql:
    image: mysql:8.0
    container_name: LaravelVue-mysql
    volumes:
      - LaravelVue-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=LaravelVue
      - MYSQL_DATABASE=LaravelVue
      - MYSQL_USER=LaravelVue
      - MYSQL_PASSWORD=LaravelVue
    networks:
      - LaravelVue-network

networks:
  LaravelVue-network:
    driver: bridge

volumes:
  LaravelVue-db:
    driver: local